name: Static Checks

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  lint-typecheck-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run TypeScript type check
        run: npm run typecheck
      - name: Run Prettier check
        run: npm run format:check 
